export function renderHomeExtras(container, trackId = "snowpro-core") {
  const root = document.createElement("div");
  root.className = "v26-home-extras";
  root.innerHTML = `<section class="v26-section"><div class="v26-section-heading"><p class="v26-kicker">Certification paths</p><h2>Choose your certification</h2></div><div class="v26-cert-grid">${card("COF-C03", "SnowPro Core", "Core", "Architecture, governance, loading, performance, and collaboration.", `#/curriculum?track_id=${trackId}`, true)}${card("DEA", "Advanced Data Engineer", "Advanced", "Advanced Snowflake data engineering and pipeline design.")}${card("ARCH", "Advanced Architect", "Advanced", "Secure, scalable Snowflake platform architecture.")}${card("AI", "Snowflake AI", "Specialty", "A future guide for Snowflake AI and Cortex capabilities.")}</div><p class="v26-center-link"><a href="#/certifications">View all certification paths →</a></p></section><section class="v26-section"><div class="v26-section-heading"><p class="v26-kicker">FAQ</p><h2>Frequently asked questions</h2></div><div class="v26-faq-list">${faq("Where should I begin?", "Start with the diagnostic, study the weak task lessons, then use drills and timed mocks to validate progress.")}${faq("Can I switch certification paths?", "Yes. Use the certification selector in the header at any time.")}${faq("Does a mock use the real Snowflake scoring formula?", "No. The practice score is a transparent readiness estimate for study purposes.")}${faq("Will a timed mock survive refresh?", "Yes. Persisted exam sessions keep answers, flags, question order, and the running deadline.")}</div></section>`;
  container.querySelector("main")?.appendChild(root);
  root.querySelectorAll(".v26-faq").forEach((item) => item.addEventListener("toggle", () => { item.querySelector("summary span").textContent = item.open ? "−" : "+"; }));
}

function card(code, title, level, body, href = "", available = false) { return `<article class="v26-cert-card ${available ? "selected" : ""}"><div class="v26-card-top"><span>${code}</span><b>${available ? "AVAILABLE" : "SOON"}</b></div><h2>${title}</h2><p>${body}</p>${available ? `<a class="v26-card-action" href="${href}">Open certification <span>→</span></a>` : `<span class="v26-card-action disabled">${level} · Coming soon</span>`}</article>`; }
function faq(question, answer) { return `<details class="v26-faq"><summary>${question}<span>+</span></summary><div><p>${answer}</p></div></details>`; }
