export function renderHomeExtras(container, trackId = "snowpro-core") {
  const root = document.createElement("div");
  root.className = "v26-home-extras";
  root.innerHTML = `<section class="v26-section"><div class="v26-section-heading"><p class="v26-kicker">Certification paths</p><h2>Choose your certification</h2></div><div class="v26-cert-grid v26-cert-grid-focused">${card("COF-C03", "SnowPro Core", "Technical Certification", "Architecture, governance, loading, performance, and collaboration.", `#/curriculum?track_id=snowpro-core`, true)}${card("DEA-C02", "SnowPro Advanced: Data Engineer", "Advanced Certification", "Production data pipelines, transformations, streams, and scalable compute.")}${card("ARA-C01", "SnowPro Advanced: Architect", "Advanced Certification", "Secure, scalable end-to-end Snowflake platform architecture.")}</div><p class="v26-center-link"><a href="#/certifications">Compare certification paths after signing in →</a></p></section><section class="v26-section v26-home-membership"><div class="v26-section-heading"><p class="v26-kicker">Membership</p><h2>Create an account first. Then choose your access.</h2></div><div class="v26-home-plan-grid"><article><span>Free account</span><strong>$0</strong><p>After creating a candidate account, unlock the included study materials, daily practice allowance, and weekly timed mock. No certification content is exposed before login.</p><a href="#/curriculum">Create account to start →</a></article><article class="premium"><span>Paid options</span><strong>From $20<small>/month + tax</small></strong><p>After signing in, choose 100, 250, or 500 daily questions—or buy the $35 one-time Exam Pack with lifetime Practice Mock access.</p><a href="#/membership">Compare all plans →</a></article></div></section><section class="v26-section"><div class="v26-section-heading"><p class="v26-kicker">FAQ</p><h2>Frequently asked questions</h2></div><div class="v26-faq-list">${faq("Do I need an account to study?", "Yes. The public site only shows product and membership information. Curriculum, lessons, reference material, practice questions, labs, journal content, progress, and mock exams require a candidate account.")}${faq("Where should I begin after signing in?", "Start with the diagnostic, study the weak task lessons, then use drills and timed mocks to validate progress.")}${faq("Can I switch certification paths?", "SnowPro Core is available now. Advanced Data Engineer and Advanced Architect are visible as Coming Soon until their content is fully authored.")}${faq("Does a mock use the real Snowflake scoring formula?", "No. The practice score is a transparent readiness estimate for study purposes.")}</div></section>`;
  container.querySelector("main")?.appendChild(root);
  root.querySelectorAll(".v26-faq").forEach((item) => item.addEventListener("toggle", () => { item.querySelector("summary span").textContent = item.open ? "−" : "+"; }));
}

function card(code, title, level, body, href = "", available = false) { return `<article class="v26-cert-card ${available ? "selected" : "coming-soon"}"><div class="v26-card-top"><span>${code}</span><b>${available ? "AVAILABLE" : "COMING SOON"}</b></div><h2>${title}</h2><p>${body}</p>${available ? `<a class="v26-card-action" href="${href}">Create account to access <span>→</span></a>` : `<span class="v26-card-action disabled">${level} · Coming Soon</span>`}</article>`; }
function faq(question, answer) { return `<details class="v26-faq"><summary>${question}<span>+</span></summary><div><p>${answer}</p></div></details>`; }
