export function renderHomeExtras(container, trackId = "snowpro-core") {
  const root = document.createElement("div");
  root.className = "v26-home-extras";
  root.innerHTML = `<section class="v26-section"><div class="v26-section-heading"><p class="v26-kicker">Certification paths</p><h2>Choose your certification</h2><p>Start with SnowPro Core. Public certification facts remain inspectable while advanced and specialty study guides stay secondary until their original content is production-ready.</p></div><div class="v26-cert-grid v26-cert-grid-focused">${card("COF-C03", "SnowPro Core", "Foundational", "Architecture, governance, loading, performance, and collaboration.", `#/curriculum?track_id=${encodeURIComponent(trackId)}`, true)}${card("ARA-C01", "SnowPro Advanced: Architect", "Advanced", "Secure, scalable end-to-end Snowflake platform architecture.")}${card("DEA-C02", "SnowPro Advanced: Data Engineer", "Advanced", "Production data pipelines, transformations, streams, and scalable compute.")}${card("SPECIALTY", "SnowPro Specialty", "Specialty", "Focused specialty preparation as additional Snowflake certification paths become production-ready.")}</div><p class="v26-center-link"><a href="#/certifications">Compare source-checked certification facts →</a></p></section>
  <section class="v26-section v26-testimonials"><div class="v26-section-heading"><p class="v26-kicker">Candidate study notes</p><h2>What focused preparation should feel like</h2><p>Four original workflow examples show how the product is designed to turn blueprint gaps into deliberate review. They are not claimed exam-pass testimonials.</p></div><div class="v26-testimonial-grid">${testimonial("The blueprint view makes the uncovered tasks obvious. Instead of rereading everything, I can close the exact objectives that still have weak evidence.", "Blueprint discipline", "Study workflow")}${testimonial("A missed question does not disappear. It becomes a mistake-notebook entry, a written rule, a targeted drill, and a later reattempt.", "Review loop", "Mistake collection")}${testimonial("Timed mocks are more useful when the result feeds readiness and tells me which weighted domain should be next rather than stopping at a score.", "Exam rehearsal", "Adaptive readiness")}${testimonial("Due Today keeps review small enough to repeat. The goal is retaining the decision rule, not just remembering the answer I saw yesterday.", "Retention", "Spaced review")}</div></section>
  <section class="v26-section v26-home-membership"><div class="v26-section-heading"><p class="v26-kicker">Membership</p><h2>Create an account first. Then choose your access.</h2></div><div class="v26-home-plan-grid"><article><span>Free account</span><strong>$0</strong><p>After creating a candidate account, unlock the included study materials, daily practice allowance, and weekly timed mock. Public exam facts remain visible before login; lessons, private questions, progress, and practice do not.</p><a href="#/curriculum">Create account to start →</a></article><article class="premium"><span>Paid options</span><strong>From $20<small>/month + tax</small></strong><p>After signing in, choose 100, 250, or 500 daily questions—or buy the $35 one-time Exam Pack with lifetime Practice Mock access.</p><a href="#/membership">Compare all plans →</a></article></div></section>
  <section class="v26-section"><div class="v26-section-heading"><p class="v26-kicker">FAQ</p><h2>Frequently asked questions</h2></div><div class="v26-faq-list">${faq("Do I need an account to study?", "Yes. Public pages can explain the product, membership, source-checked certification facts, trust, and policies. Curriculum, lessons, reference material, practice questions, labs, journal content, progress, and mock exams require a candidate account.")}${faq("Where should I begin after signing in?", "Start with the diagnostic, study the weak task lessons, then use drills and timed mocks to validate progress.")}${faq("Can I switch certification paths?", "SnowPro Core is available now. Other paths may expose verified public exam facts before their Snowflake Brain study guides are fully authored and reviewed.")}${faq("Does a mock use the real Snowflake scoring formula?", "No. The practice score is a transparent readiness estimate for study purposes.")}${faq("How is my progress used?", "Practice attempts, mistakes, spaced-review state, mock history, and study preferences are used to build your readiness evidence and next-study recommendations.")}</div></section>`;
  container.querySelector("main")?.appendChild(root);
  root.querySelectorAll(".v26-faq").forEach((item) => item.addEventListener("toggle", () => { item.querySelector("summary span").textContent = item.open ? "−" : "+"; }));
}

function card(code, title, level, body, href = "", available = false) { return `<article class="v26-cert-card ${available ? "selected" : "coming-soon"}"><div class="v26-card-top"><span>${code}</span><b>${available ? "AVAILABLE" : "COMING SOON"}</b></div><h2>${title}</h2><p>${body}</p><footer><span>${level}</span>${available ? `<a class="v26-card-action" href="${href}">Open guide <span>→</span></a>` : `<a class="v26-card-action" href="#/certifications">View exam facts <span>→</span></a>`}</footer></article>`; }
function faq(question, answer) { return `<details class="v26-faq"><summary>${question}<span>+</span></summary><div><p>${answer}</p></div></details>`; }
function testimonial(body, title, context) { return `<article class="v26-testimonial"><p>“${body}”</p><footer><strong>${title}</strong><span>${context}</span></footer></article>`; }
