(() => {
  const D = window.DEMO_DATA;
  const KEY = "snowflake-demo-v1-state";
  const defaults = { theme:"light", targetDate:"", completedLessons:8, practiceAnswered:0, practiceCorrect:0, mistakes:{}, mastered:{}, currentQuestionIndex:0, practiceOrder:D.questions.map(q=>q.id) };
  let state;
  try { state = { ...defaults, ...JSON.parse(localStorage.getItem(KEY)||"{}") }; } catch { state = { ...defaults }; }
  let mistakeFilter="all", selectedAnswer=null, answerRevealed=false;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const view=$("#routeView");
  const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));updateNav();};
  const route=()=>((location.hash||"#home").slice(1).split("?")[0]||"home");
  const currentQuestion=()=>D.questions.find(q=>q.id===state.practiceOrder[state.currentQuestionIndex%state.practiceOrder.length])||D.questions[0];
  const domain=id=>D.certification.domains.find(d=>d.id===id)||D.certification.domains[0];
  const unmastered=()=>Object.keys(state.mistakes).filter(id=>!state.mastered[id]).length;
  const readiness=()=>Math.max(0,Math.min(99,Math.round(D.certification.domains.reduce((s,d)=>s+d.readiness*d.weight,0)/100+Math.min(4,Math.floor(state.practiceCorrect/3))-unmastered()*.6)));
  const daysUntil=d=>{if(!d)return null;const a=new Date(d+"T12:00:00"),b=new Date();b.setHours(12,0,0,0);return Math.ceil((a-b)/86400000)};
  function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),1800)}
  function updateNav(){const c=$("#mistakeNavCount");if(c)c.textContent=Object.keys(state.mistakes).length}
  function activeNav(r){const g=r.startsWith("domain/")?"study":r.startsWith("practice/")?"practice":r;$$('[data-nav]').forEach(a=>a.classList.toggle("active",a.dataset.nav===g))}
  function domainCard(d){return `<article class="card domain-card"><div class="domain-top"><span class="domain-num">D${d.number}</span><span class="weight-badge">${d.weight}% of exam</span></div><h3>${d.name}</h3><div class="domain-meta"><span>${d.tasks.length} objectives</span><span>${d.questionCount} mapped questions</span></div><div class="progress-track"><div class="progress-fill" style="width:${d.readiness}%"></div></div><div class="domain-footer"><span class="muted">Readiness</span><strong>${d.readiness}%</strong></div><a class="text-link" href="#domain/${d.id}">Enter domain →</a></article>`}
  function home(){const r=readiness(),days=daysUntil(state.targetDate);return `<div class="page"><section class="hero"><div class="hero-copy"><span class="eyebrow">${D.certification.name} · ${D.certification.code}</span><h1>Prepare with <span>evidence</span>, not endless content.</h1><p>Build exam readiness through blueprint-mapped lessons, targeted practice, mistake remediation and realistic SnowPro Core mock exams.</p><div class="cta-row"><a class="button primary" href="#practice">Start practice →</a><a class="button" href="#study">Browse study guide</a></div></div><div class="hero-side"><div class="readiness-ring" style="--value:${r}"><div class="readiness-value"><strong>${r}%</strong><span>Exam readiness</span></div></div><div class="hero-side-note">${days===null?"Set a target exam date to pace your plan.":days>=0?`${days} days until your target exam date.`:"Your target date has passed — update it in Readiness."}</div></div></section><section class="metric-grid"><div class="metric-card"><strong>${D.certification.questions.toLocaleString()}</strong><span>Mapped practice questions</span></div><div class="metric-card"><strong>5</strong><span>Weighted exam domains</span></div><div class="metric-card"><strong>${D.certification.tasks}</strong><span>Blueprint objectives</span></div><div class="metric-card"><strong>${D.certification.mockQuestions}</strong><span>Full mock questions</span></div></section><section class="section"><div class="section-heading"><div><h2>Continue where you left off</h2><p>Your next recommended learning action.</p></div></div><div class="card continue-card"><div><span class="eyebrow">Weakest domain · Performance</span><h3>Task 4.2 — Warehouse performance</h3><p>Continue with scale up vs scale out, queueing and concurrency decisions.</p></div><a class="button primary" href="#domain/performance">Resume lesson →</a></div></section><section class="section"><div class="section-heading"><div><h2>Your exam blueprint</h2><p>Five domains, weighted exactly once across the learning experience.</p></div><a class="text-link" href="#study">Full study guide →</a></div><div class="grid-3">${D.certification.domains.map(domainCard).join("")}</div></section><section class="section"><div class="section-heading"><div><h2>Today</h2><p>A focused queue instead of an endless dashboard.</p></div></div><div class="today-grid"><div class="card today-card"><span>Due for review</span><strong>18</strong><small>lessons & concepts</small></div><div class="card today-card"><span>Unmastered mistakes</span><strong>${unmastered()}</strong><small>ready to remediate</small></div><div class="card today-card"><span>Practice accuracy</span><strong>${state.practiceAnswered?Math.round(state.practiceCorrect/state.practiceAnswered*100):0}%</strong><small>${state.practiceAnswered} answered in this demo</small></div></div></section></div>`}
  function study(){return `<div class="page"><header class="page-head"><div><span class="eyebrow">Blueprint mapped</span><h1>Study Guide</h1><p>Move from certification domain → exam objective → knowledge point. Every lesson remains tied to what the exam evaluates.</p></div><a class="button primary" href="#practice">Practice weak topics</a></header><div class="study-layout"><section class="domain-list">${D.certification.domains.map((d,i)=>`<article class="domain-row ${i===0?"open":""}"><div class="domain-row-main"><span class="domain-num">D${d.number}</span><div><h3>${d.name}</h3><p>${d.weight}% of exam · ${d.tasks.length} objectives · ${d.questionCount} questions mapped</p></div><span class="chevron">›</span></div><div class="task-list">${d.tasks.map(t=>`<a class="task-item" href="#domain/${d.id}?task=${t.id}"><span class="task-id">${t.id}</span><strong>${t.title}</strong><small>${t.lessons.length} topics →</small></a>`).join("")}</div></article>`).join("")}</section><aside class="blueprint-side card"><div class="card-pad"><span class="eyebrow">Coverage snapshot</span><h3>COF-C03 domains</h3>${D.certification.domains.map(d=>`<div class="legend-row"><span>D${d.number} · ${d.short}</span><strong>${d.weight}%</strong></div>`).join("")}</div></aside></div></div>`}
  function domainPage(id){const d=domain(id),params=new URLSearchParams((location.hash.split("?")[1]||"")),selected=params.get("task");return `<div class="page"><header class="page-head"><div><span class="eyebrow">Domain ${d.number} · ${d.weight}%</span><h1>${d.short}</h1><p>${d.name}</p></div><a class="button primary" href="#practice">Practice this domain</a></header><div class="card card-pad" style="margin-bottom:16px"><div class="domain-meta"><span>${d.questionCount} questions mapped</span><span>${d.tasks.length} objectives</span><span>${d.readiness}% current readiness</span></div><div class="progress-track" style="margin-top:12px"><div class="progress-fill" style="width:${d.readiness}%"></div></div></div><div class="domain-list">${d.tasks.map(t=>`<article class="card card-pad" style="${selected===t.id?"outline:2px solid var(--brand)":""}"><span class="eyebrow">Task ${t.id}</span><h3 style="margin:8px 0 14px">${t.title}</h3><div class="grid-2">${t.lessons.map((l,i)=>`<div class="task-item"><span class="task-id">${String(i+1).padStart(2,"0")}</span><strong>${l}</strong><button class="button small lesson-complete">${i<1?"Review":"Study"}</button></div>`).join("")}</div></article>`).join("")}</div></div>`}
  function practice(){const modes=[{icon:"⚡",title:"Quick Practice",desc:"A short mixed-domain session for daily repetition and fast feedback.",meta:["10–15 questions","Mixed domains"],href:"#practice/session",action:"Start quick practice"},{icon:"◎",title:"Adaptive Practice",desc:"Prioritize weaker domains and recently missed concepts as readiness changes.",meta:["Weakness driven","Readiness aware"],href:"#practice/session",action:"Start adaptive"},{icon:"△",title:"Advanced Practice",desc:"Higher-difficulty scenario and architecture-decision questions for exam judgment.",meta:["Exam difficulty","Scenario heavy"],href:"#practice/session",action:"Start advanced"},{icon:"↺",title:"Redo Mistakes",desc:"Reattempt concepts you missed and move them from unmastered to mastered.",meta:[`${unmastered()} unmastered`,`Remediation`],href:"#mistakes",action:"Review mistakes"}];return `<div class="page"><header class="page-head"><div><span class="eyebrow">Practice engine</span><h1>Practice with purpose</h1><p>Choose daily repetition, weak-area remediation, difficult scenarios, or mistake review.</p></div></header><div class="grid-2">${modes.map(m=>`<article class="card mode-card"><span class="mode-icon">${m.icon}</span><div><h3>${m.title}</h3><p>${m.desc}</p></div><div class="mode-meta">${m.meta.map(x=>`<span class="chip">${x}</span>`).join("")}</div><a class="button primary" href="${m.href}">${m.action} →</a></article>`).join("")}</div><section class="section"><div class="section-heading"><div><h2>Practice by domain</h2><p>Use weighted pools to target one part of the blueprint.</p></div></div><div class="grid-3">${D.certification.domains.map(domainCard).join("")}</div></section></div>`}
  function session(){const q=currentQuestion(),d=domain(q.domain);return `<div class="page question-shell"><div class="question-top"><a class="button small" href="#practice">← Exit</a><div class="question-progress"><small><span>Question ${state.currentQuestionIndex+1} of ${state.practiceOrder.length}</span><span>${state.practiceCorrect} correct</span></small><div class="progress-track"><div class="progress-fill" style="width:${state.currentQuestionIndex/state.practiceOrder.length*100}%"></div></div></div></div><article class="card question-card"><div class="question-tags"><span class="chip brand">${d.short}</span><span class="chip">Task ${q.task}</span><span class="chip">${q.difficulty}</span><span class="chip">${q.type}</span></div><h2>${q.stem}</h2><div class="option-list">${q.options.map((o,i)=>`<button class="option" data-option="${i}"><span class="option-letter">${String.fromCharCode(65+i)}</span><span>${o}</span></button>`).join("")}</div><div id="feedbackSlot"></div><div class="question-actions"><button class="button ghost" id="flagQuestion">Flag for review</button><button class="button primary" id="submitAnswer" disabled>Check answer</button></div></article></div>`}
  function mistakes(){const ids=Object.keys(state.mistakes),mastered=ids.filter(id=>state.mastered[id]).length,visible=ids.filter(id=>mistakeFilter==="all"||(mistakeFilter==="mastered"?state.mastered[id]:!state.mastered[id]));return `<div class="page"><header class="page-head"><div><span class="eyebrow">Remediation loop</span><h1>Mistake Collection</h1><p>Incorrect answers are saved automatically. Review why you missed them, reattempt the concept, and mark it mastered.</p></div><a class="button primary" href="#practice/session">Practice again</a></header><div class="metric-grid"><div class="metric-card"><strong>${ids.length}</strong><span>Total mistakes</span></div><div class="metric-card"><strong>${ids.length-mastered}</strong><span>Unmastered</span></div><div class="metric-card"><strong>${mastered}</strong><span>Mastered</span></div><div class="metric-card"><strong>${ids.length?Math.round(mastered/ids.length*100):0}%</strong><span>Mastery rate</span></div></div><div class="filter-row"><button class="filter-button ${mistakeFilter==="all"?"active":""}" data-mfilter="all">All (${ids.length})</button><button class="filter-button ${mistakeFilter==="unmastered"?"active":""}" data-mfilter="unmastered">Unmastered (${ids.length-mastered})</button><button class="filter-button ${mistakeFilter==="mastered"?"active":""}" data-mfilter="mastered">Mastered (${mastered})</button></div>${visible.length?`<div class="mistake-list">${visible.map(id=>{const q=D.questions.find(x=>x.id===id),rec=state.mistakes[id],d=domain(q.domain);return `<article class="card mistake-card"><div class="mistake-meta"><div><span class="chip brand">${d.short}</span> <span class="chip">Task ${q.task}</span></div><span class="chip ${state.mastered[id]?"success":"danger"}">${state.mastered[id]?"Mastered":"Unmastered"}</span></div><h3>${q.stem}</h3><div class="mistake-answer"><span>Your answer</span><strong>${q.options[rec.selected]}</strong><span>Correct answer</span><strong>${q.options[q.answer]}</strong><span>Why</span><div>${q.wrongWhy}</div></div><div class="mistake-actions"><button class="button small retry-mistake" data-qid="${id}">Retry concept</button><button class="button small toggle-mastered" data-qid="${id}">${state.mastered[id]?"Mark unmastered":"Mark mastered"}</button><a class="button small" href="#domain/${q.domain}?task=${q.task}">Related lesson</a></div></article>`}).join("")}</div>`:`<div class="card empty-state"><div class="empty-icon">✓</div><h3>${ids.length?"No mistakes in this filter":"Your mistake collection is empty"}</h3><p>${ids.length?"Switch filters or return to practice.":"Answer a practice question incorrectly and it will appear here automatically with remediation guidance."}</p><a class="button primary" href="#practice/session">Start practice</a></div>`}</div>`}
  function progress(){const r=readiness(),days=daysUntil(state.targetDate);return `<div class="page"><header class="page-head"><div><span class="eyebrow">Learning intelligence</span><h1>Exam Readiness</h1><p>Readiness combines weighted domain performance with practice signals and unresolved mistakes in this demo model.</p></div></header><div class="readiness-layout"><section class="card readiness-panel"><div class="readiness-ring" style="--value:${r}"><div class="readiness-value"><strong>${r}%</strong><span>Ready</span></div></div><h2>${r>=80?"Strong trajectory":r>=70?"Building confidence":"Focus weak domains"}</h2><p>${days===null?"Set your exam date below to turn readiness into a paced plan.":days>=0?`${days} days remain until your target exam date.`:"Update your target exam date."}</p></section><section class="card domain-bars"><span class="eyebrow">Domain mastery</span><h3>Weighted performance</h3>${D.certification.domains.map(d=>`<div class="bar-row"><span>${d.short}</span><div class="progress-track"><div class="progress-fill" style="width:${d.readiness}%"></div></div><strong>${d.readiness}%</strong></div>`).join("")}</section></div><section class="card exam-date-box"><div><label for="targetDate">Target exam date</label><div class="muted" style="font-size:11px">Use a date to pace study intensity and mock frequency.</div></div><div><input class="date-input" type="date" id="targetDate" value="${state.targetDate}"> <button class="button small primary" id="saveDate">Save</button></div></section><section class="section"><div class="section-heading"><div><h2>Recommended next actions</h2><p>Based on the weakest areas visible in this demo.</p></div></div><div class="grid-3"><article class="card mode-card"><span class="mode-icon">1</span><h3>Performance remediation</h3><p>Review Task 4.2, then answer targeted questions on warehouse scaling.</p><a class="button" href="#domain/performance">Review domain →</a></article><article class="card mode-card"><span class="mode-icon">2</span><h3>Clear mistakes</h3><p>Resolve unmastered mistakes before taking another full mock.</p><a class="button" href="#mistakes">Open mistakes →</a></article><article class="card mode-card"><span class="mode-icon">3</span><h3>Mock checkpoint</h3><p>Use a timed checkpoint after weak-domain remediation.</p><a class="button" href="#mock">Choose mock →</a></article></div></section></div>`}
  function mock(){return `<div class="page"><header class="page-head"><div><span class="eyebrow">Exam simulation</span><h1>Mock Exams</h1><p>Use short checkpoints for iteration and a full weighted simulation when you are ready to measure exam stamina.</p></div></header><div class="grid-2"><article class="card mode-card"><span class="mode-icon">◷</span><h3>Quick Mock</h3><p>A shorter timed checkpoint that samples all five exam domains.</p><div class="mode-meta"><span class="chip">30 questions</span><span class="chip">45 minutes</span><span class="chip">Weighted</span></div><button class="button primary demo-mock">Start quick mock →</button></article><article class="card mode-card"><span class="mode-icon">◎</span><h3>Full COF-C03 Simulation</h3><p>A full-length practice simulation designed around the weighted blueprint used throughout the platform.</p><div class="mode-meta"><span class="chip">100 questions</span><span class="chip">120 minutes</span><span class="chip">Full report</span></div><button class="button primary demo-mock">Start full mock →</button></article></div><section class="section"><div class="card card-pad"><span class="eyebrow">Result design</span><h3>Every mock should produce action</h3><div class="grid-3"><div class="task-item"><span class="task-id">01</span><strong>Overall score</strong><small>pass threshold view</small></div><div class="task-item"><span class="task-id">02</span><strong>Domain breakdown</strong><small>weighted gaps</small></div><div class="task-item"><span class="task-id">03</span><strong>Remediation queue</strong><small>mistakes → lessons</small></div></div></div></section></div>`}
  function cheat(){return `<div class="page"><header class="page-head"><div><span class="eyebrow">Fast recall</span><h1>Cheat Sheet</h1><p>Compact references for high-confusion comparisons and exam decision patterns.</p></div></header><div class="cheat-grid">${D.cheatSheets.map(c=>`<article class="card cheat-card"><span class="chip brand">${c.tag}</span><h3>${c.title}</h3><p>${c.body}</p></article>`).join("")}</div><section class="section"><div class="section-heading"><div><h2>Decision trees</h2><p>Scenario cues → best-fit Snowflake capability.</p></div></div><div class="grid-2"><article class="card decision-card"><h3>Scale up or scale out?</h3><div class="decision-flow"><div class="decision-step"><strong>One query needs more compute?</strong> Consider scaling the warehouse up.</div><div class="decision-step"><strong>Many fast queries are queueing?</strong> Consider multi-cluster / scale-out concurrency.</div><div class="decision-step"><strong>Still scanning too much?</strong> Diagnose pruning and query design before assuming compute is the answer.</div></div></article><article class="card decision-card"><h3>COPY or Snowpipe?</h3><div class="decision-flow"><div class="decision-step"><strong>Controlled batch load?</strong> COPY INTO is the common exam cue.</div><div class="decision-step"><strong>Files arrive continuously and should auto-ingest?</strong> Snowpipe is the common cue.</div><div class="decision-step"><strong>Low-latency streaming events?</strong> Recognize streaming-specific choices rather than file loading.</div></div></article></div></section></div>`}
  const communityCard=c=>`<article class="card community-card" data-community-domain="${c.domain}"><span class="chip brand">${c.type}</span> <span class="chip">${c.domain}</span><h3>${c.title}</h3><p>${c.text}</p></article>`;
  function community(){return `<div class="page"><header class="page-head"><div><span class="eyebrow">Shared learning</span><h1>Community Insights</h1><p>Study strategies, common mistakes and exam-pattern observations organized around SnowPro domains.</p></div><button class="button" id="shareInsight">Share an insight</button></header><div class="filter-row">${["All",...D.certification.domains.map(d=>d.short)].map((x,i)=>`<button class="filter-button ${i===0?"active":""}" data-community-filter="${x}">${x}</button>`).join("")}</div><div class="grid-2">${D.community.map(communityCard).join("")}</div></div>`}
  function resources(){return `<div class="page"><header class="page-head"><div><span class="eyebrow">Knowledge hub</span><h1>Resources</h1><p>Exam facts, study plans, domain deep dives and technical guides designed to reinforce the learning engine.</p></div></header><div class="grid-2">${D.resources.map(r=>`<article class="card resource-card"><span class="chip brand">${r.category}</span><h3>${r.title}</h3><p>${r.description}</p><a class="text-link" href="#study">Explore guide →</a></article>`).join("")}</div><section class="section"><div class="card card-pad"><span class="eyebrow">Trust boundary</span><h3>Independent certification preparation</h3><p class="muted" style="font-size:12px;line-height:1.65">This demo captures product patterns without copying competitor branding, proprietary articles, or live-exam material. Production should link to official Snowflake certification sources for authoritative exam policies and updates.</p></div></section></div>`}
  function account(){return `<div class="page"><header class="page-head"><div><span class="eyebrow">Learner profile</span><h1>Account</h1><p>Manage study preferences, local demo state and the eventual connection to verified certification credentials.</p></div></header><div class="account-grid"><section class="card account-card"><h3>Profile</h3><div class="account-row"><span>Name</span><strong>Demo Learner</strong></div><div class="account-row"><span>Track</span><strong>SnowPro Core · COF-C03</strong></div><div class="account-row"><span>Theme</span><strong>${state.theme}</strong></div><div class="account-row"><span>Target exam</span><strong>${state.targetDate||"Not set"}</strong></div></section><section class="card account-card"><h3>Learning data</h3><div class="account-row"><span>Practice answered</span><strong>${state.practiceAnswered}</strong></div><div class="account-row"><span>Mistakes saved</span><strong>${Object.keys(state.mistakes).length}</strong></div><div class="account-row"><span>Mastered mistakes</span><strong>${Object.keys(state.mastered).filter(id=>state.mastered[id]).length}</strong></div><div class="account-row"><span>Readiness</span><strong>${readiness()}%</strong></div><button class="button danger" id="resetDemo" style="margin-top:16px">Reset demo learning data</button></section></div><section class="section"><div class="card card-pad"><span class="eyebrow">Production integration</span><h3>Verified credentials</h3><p class="muted" style="font-size:12px;line-height:1.65">The full platform already has a verified-credential foundation. This fresh demo keeps the public experience lightweight while production owns account verification and credential workflows.</p></div></section></div>`}
  function render(){const r=route();activeNav(r);selectedAnswer=null;answerRevealed=false;if(r==="home")view.innerHTML=home();else if(r==="study")view.innerHTML=study();else if(r.startsWith("domain/"))view.innerHTML=domainPage(r.split("/")[1]);else if(r==="practice")view.innerHTML=practice();else if(r==="practice/session")view.innerHTML=session();else if(r==="mistakes")view.innerHTML=mistakes();else if(r==="progress")view.innerHTML=progress();else if(r==="mock")view.innerHTML=mock();else if(r==="cheatsheet")view.innerHTML=cheat();else if(r==="community")view.innerHTML=community();else if(r==="resources")view.innerHTML=resources();else if(r==="account")view.innerHTML=account();else view.innerHTML=`<div class="page"><div class="card empty-state"><div class="empty-icon">?</div><h3>Page not found</h3><p>The route does not exist in this demo.</p><a class="button primary" href="#home">Go home</a></div></div>`;bind();updateNav();window.scrollTo(0,0)}
  function bind(){
    $$(".domain-row-main").forEach(el=>el.addEventListener("click",()=>el.closest(".domain-row").classList.toggle("open")));
    $$(".lesson-complete").forEach(b=>b.addEventListener("click",()=>{state.completedLessons++;save();b.textContent="Done ✓";b.classList.add("primary");toast("Lesson progress saved")}));
    $$(".option").forEach(b=>b.addEventListener("click",()=>{if(answerRevealed)return;selectedAnswer=Number(b.dataset.option);$$(".option").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");$("#submitAnswer").disabled=false}));
    $("#submitAnswer")?.addEventListener("click",function check(){if(selectedAnswer===null||answerRevealed)return;const q=currentQuestion(),ok=selectedAnswer===q.answer;answerRevealed=true;state.practiceAnswered++;if(ok){state.practiceCorrect++;if(state.mistakes[q.id])state.mastered[q.id]=true}else{state.mistakes[q.id]={selected:selectedAnswer,at:Date.now()};state.mastered[q.id]=false}save();$$(".option").forEach((o,i)=>{o.disabled=true;if(i===q.answer)o.classList.add("correct");if(i===selectedAnswer&&!ok)o.classList.add("incorrect")});$("#feedbackSlot").innerHTML=`<div class="feedback-box ${ok?"correct":"incorrect"}"><strong>${ok?"Correct":"Not quite"}</strong><p>${q.explanation}</p></div>`;this.textContent=state.currentQuestionIndex+1>=state.practiceOrder.length?"Finish session":"Next question →";this.disabled=false;this.onclick=()=>{state.currentQuestionIndex=(state.currentQuestionIndex+1)%state.practiceOrder.length;save();render()}});
    $("#flagQuestion")?.addEventListener("click",()=>toast("Flagged for review in this demo session"));
    $$('[data-mfilter]').forEach(b=>b.addEventListener("click",()=>{mistakeFilter=b.dataset.mfilter;render()}));
    $$(".toggle-mastered").forEach(b=>b.addEventListener("click",()=>{state.mastered[b.dataset.qid]=!state.mastered[b.dataset.qid];save();render()}));
    $$(".retry-mistake").forEach(b=>b.addEventListener("click",()=>{const i=state.practiceOrder.indexOf(b.dataset.qid);if(i>=0)state.currentQuestionIndex=i;save();location.hash="#practice/session"}));
    $("#saveDate")?.addEventListener("click",()=>{state.targetDate=$("#targetDate").value;save();toast("Target exam date saved");render()});
    $$(".demo-mock").forEach(b=>b.addEventListener("click",()=>toast("Mock session engine is the next implementation slice")));
    $("#shareInsight")?.addEventListener("click",()=>toast("Community contribution workflow is reserved for the next slice"));
    $$('[data-community-filter]').forEach(b=>b.addEventListener("click",()=>{$$('[data-community-filter]').forEach(x=>x.classList.remove("active"));b.classList.add("active");$$('[data-community-domain]').forEach(c=>c.style.display=b.dataset.communityFilter==="All"||c.dataset.communityDomain===b.dataset.communityFilter?"block":"none")}));
    $("#resetDemo")?.addEventListener("click",()=>{if(!confirm("Reset all local demo learning data?"))return;state={...defaults,theme:state.theme,practiceOrder:[...defaults.practiceOrder]};save();render();toast("Demo data reset")});
  }
  $("#themeToggle").addEventListener("click",()=>{state.theme=state.theme==="dark"?"light":"dark";save();document.documentElement.dataset.theme=state.theme;toast(`${state.theme==="dark"?"Dark":"Light"} theme enabled`)});
  $("#menuToggle").addEventListener("click",()=>$("#sidebar").classList.toggle("open"));
  $("#sidebar").addEventListener("click",e=>{if(e.target.closest("a")&&innerWidth<760)$("#sidebar").classList.remove("open")});
  window.addEventListener("hashchange",render);document.documentElement.dataset.theme=state.theme;updateNav();render();
})();
